spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  datasource:
    url: jdbc:mysql://43.129.190.58:3306/test
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      aop-patterns: com.yz.admin.*  #监控SpringBean
      filters: stat,wall     # 底层开启功能，stat（sql监控），wall（防火墙）

      stat-view-servlet:  # 配置监控页功能
        enabled: true
        login-username: admin
        login-password: admin
        reset-enable: false

      web-stat-filter:  # 监控web
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'


      filter:
        stat:    # 对上面filters里面的stat的详细配置
          slow-sql-millis: 1000
          log-slow-sql: true
          enabled: true
        wall:
          enabled: true
          config:
            drop-table-allow: false


  redis:
    host: 43.129.190.58
    port: 6379
    password:
    client-type: jedis
    jedis:
      pool:
        max-active: 10





  jdbc:
    template:
      query-timeout: 3


# 配置mybatis规则
#mybatis:
  ##  config-location: classpath:mybatis/mybatis-config.xml
#  mapper-locations: classpath:mapper/*.xml
# configuration:
#    map-underscore-to-camel-case: true